export const ActionType = {
  FETCH_BY_SEARCH: "FETCH_BY_SEARCH",
  FETCH_ALL: "FETCH_ALL",
  FETCH_POST: "FETCH_POST",
  CREATE_POST: "CREATE_POST",
  UPDATE_POST: "UPDATE_POST",
  DELETE_POST: "DELETE_POST",
  LIKE_POST: "LIKE_POST",
  COMMENT_POST: "COMMENT_POST",
  START_LOADING: "START_LOADING",
  END_LOADING: "END_LOADING",

  AUTH: "AUTH",
  LOGOUT: "LOGOUT",
};
